parameters:
#    auto_main.example.class: Auto\MainBundle\Example

services:
#    auto_main.example:
#        class: %auto_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    auto.form.type.tel:
         class: Auto\MainBundle\Form\Type\TelType
         tags:
             - { name: form.type, alias: tel }
